"use client"
import { useTranslations } from "next-intl";

export function getData(){
    const t = useTranslations();
    return [
        {
            number:1,
            title:t("tradeTest.welding"),
            description:t("tradeTest.weldingDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:2,
            title:t("tradeTest.carpentry"),
            description:t("tradeTest.carpentryDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:3,
            title:t("tradeTest.trailer"),
            description:t("tradeTest.trailerDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:4,
            title:t("tradeTest.masonry"),
            description:t("tradeTest.masonryDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:5,
            title:t("tradeTest.painting"),
            description:t("tradeTest.paintingDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:6,
            title:t("tradeTest.scaffolding"),
            description:t("tradeTest.scaffoldingDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:7,
            title:t("tradeTest.heavy"),
            description:t("tradeTest.heavyDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:8,
            title:t("tradeTest.caregiving"),
            description:t("tradeTest.caregivingDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:9,
            title:t("tradeTest.food"),
            description:t("tradeTest.foodDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        },
        {
            number:10,
            title:t("tradeTest.house"),
            description:t("tradeTest.cleaningDesc"),
            videoId:"1vIU3R-BIDQ",
            image1:"/img/defaultImage.png",
            image2:"/img/defaultImage.png"
        }
    ]
}