import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import CustomHR from "@/components/CustomHR";
import Navigation from "@/components/Navigation";
import Footer from "@/components/Footer";

import '../../node_modules/bootstrap/dist/css/bootstrap.min.css';

import BootstrapClient from "@/components/bootstrap-client";
import { Montserrat } from "next/font/google";

import "../../node_modules/swiper/swiper-bundle.min.css";

const montserrat = Montserrat({
        subsets: ["latin"]
    });


export const metadata: Metadata = {
  title: "Placewell International",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body style={{margin:"0px"}} className={`${montserrat.className} font-sans`}>
        <BootstrapClient />
        <CustomHR />
        <Navigation />
          {children}
        <Footer />
      </body>
    </html>
  );
}
